spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estudai
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
    defer-datasource-initialization: true


  sql:
    init:
      mode: always
      data-locations: classpath:import.sql
      continue-on-error: true
      encoding: UTF-8

  mail:
    host: smtp.gmail.com
    port: 587
    username: gabriel050monteiro@gmail.com
    password: fsis wbjd lzqn qruu
    properties:
      mail.smtp:
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

jwt:
  secret: sIsVALERKBHu+Yj57rBWrKmaHhz9UHROYwtR9RN2DLw=
  expiration: 86400000

estudai:
  email:
    sender-name: "Equipe Estudai"
    # Use 'true' para enviar emails reais em dev, 'false' para usar mock
    use-real-email: true
  allowed-domains:
    - "gmail.com"
    - "estudante.rs.gov.br"
    - "escola.com"
    - "hotmail.com"
    - "outlook.com"
    - "yahoo.com"

logging:
  level:
    br.com.fundatec.estudai: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE